import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sunny Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-10 bg-white md:px-20 lg:px-40 ">
        <section className="min-h-screen ">
          <nav className="flex justify-between py-10 mb-12">
            <h1 className="text-xl font-burtons">Sunny</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="text-2xl cursor-pointer" />
              </li>
              <li>
                <a
                  className="px-4 py-2 ml-8 text-white border-none rounded-md bg-gradient-to-r from-cyan-500 to-teal-500"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="p-10 py-10 text-center ">
            <h2 className="py-2 text-5xl font-medium text-teal-600 md:text-6xl">
              Sunny Thapa
            </h2>
            <h3 className="py-2 text-2xl md:text-3xl">
              Developer and designer.
            </h3>
            <p className="max-w-lg py-5 mx-auto leading-8 text-gray-800 text-md md:text-xl">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum neque
              sint recusandae, laudantium pariatur voluptates consequuntur
              ipsum. Eius, eos facilis.
            </p>
          </div>
          <div className="flex justify-center gap-16 text-5xlx`">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className="relative mx-auto mt-20 overflow-hidden rounded-full bg-gradient-to-b from-teal-500 w-80 h-80 md:h-96 md:w-96 ">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
        </section>
        {/*  */}
        <section>
          <div>
            <h3 className="py-1 text-3xl">Services I Offer</h3>
            <p className="py-2 leading-8 text-gray-800 text-md">
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Distinctio consequatur nostrum molestias quidem.
              <span className="text-teal-500">Agencies</span> Lorem, ipsum.{" "}
              <span className="text-teal-500">Lorem, ipsum.</span>Lorem ipsum
              dolor, sit amet consectetur adipisicing elit. Atque, nisi. Nobis
              praesentium quas cupiditate ipsam asperiores ipsum deleniti odit
              dolor.
            </p>
            <p className="py-2 leading-8 text-gray-800 text-md">
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Distinctio consequatur nostrum molestias quidem. dolor.
            </p>
          </div>
          <div className="gap-10 lg:flex">
            <div className="p-10 my-10 text-center shadow-lg rounded-xl">
              <Image src={design} width={100} height={100} />
              <h3 className="pt-8 pb-2 text-lg font-medium">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Lorem, ipsum dolor sit amet consectetur adipisicing elit.
                Blanditiis quia explicabo fuga natus pariatur iusto saepe hic
                amet mollitia? Facilis!
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="py-1 text-gray-800">Photoshop</p>
              <p className="py-1 text-gray-800">Illustrator</p>
              <p className="py-1 text-gray-800">Figma</p>
            </div>
            <div>
              <h3 className="py-1 text-3xl">Services I Offer</h3>
              <p className="py-2 leading-8 text-gray-800 text-md">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Distinctio consequatur nostrum molestias quidem.
                <span className="text-teal-500">Agencies</span> Lorem, ipsum.{" "}
                <span className="text-teal-500">Lorem, ipsum.</span>Lorem ipsum
                dolor, sit amet consectetur adipisicing elit. Atque, nisi. Nobis
                praesentium quas cupiditate ipsam asperiores ipsum deleniti odit
                dolor.
              </p>
              <p className="py-2 leading-8 text-gray-800 text-md">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Distinctio consequatur nostrum molestias quidem. dolor.
              </p>
            </div>
            <div>
              <div className="p-10 my-10 text-center shadow-lg rounded-xl">
                <Image src={code} width={100} height={100} />
                <h3 className="pt-8 pb-2 text-lg font-medium">
                  Beautiful Designs
                </h3>
                <p className="py-2">
                  Lorem, ipsum dolor sit amet consectetur adipisicing elit.
                  Blanditiis quia explicabo fuga natus pariatur iusto saepe hic
                  amet mollitia? Facilis!
                </p>
                <h4 className="py-4 text-teal-600">Design tools I use</h4>
                <p className="py-1 text-gray-800">Photoshop</p>
                <p className="py-1 text-gray-800">Illustrator</p>
                <p className="py-1 text-gray-800">Figma</p>
              </div>
            </div>
            <div>
              <h3 className="py-1 text-3xl">Services I Offer</h3>
              <p className="py-2 leading-8 text-gray-800 text-md">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Distinctio consequatur nostrum molestias quidem.
                <span className="text-teal-500">Agencies</span> Lorem, ipsum.{" "}
                <span className="text-teal-500">Lorem, ipsum.</span>Lorem ipsum
                dolor, sit amet consectetur adipisicing elit. Atque, nisi. Nobis
                praesentium quas cupiditate ipsam asperiores ipsum deleniti odit
                dolor.
              </p>
              <p className="py-2 leading-8 text-gray-800 text-md">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Distinctio consequatur nostrum molestias quidem. dolor.
              </p>
            </div>
            <div>
              <div className="p-10 my-10 text-center shadow-lg rounded-xl">
                <Image src={consulting} width={100} height={100} />
                <h3 className="pt-8 pb-2 text-lg font-medium">
                  Beautiful Designs
                </h3>
                <p className="py-2">
                  Lorem, ipsum dolor sit amet consectetur adipisicing elit.
                  Blanditiis quia explicabo fuga natus pariatur iusto saepe hic
                  amet mollitia? Facilis!
                </p>
                <h4 className="py-4 text-teal-600">Design tools I use</h4>
                <p className="py-1 text-gray-800">Photoshop</p>
                <p className="py-1 text-gray-800">Illustrator</p>
                <p className="py-1 text-gray-800">Figma</p>
              </div>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="py-1 text-3xl">Portfolio</h3>
            <p className="py-2 leading-8 text-gray-800 text-md">
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Distinctio consequatur nostrum molestias quidem.
              <span className="text-teal-500">Agencies</span> Lorem, ipsum.{" "}
              <span className="text-teal-500">Lorem, ipsum.</span>Lorem ipsum
              dolor, sit amet consectetur adipisicing elit. Atque, nisi. Nobis
              praesentium quas cupiditate ipsam asperiores ipsum deleniti odit
              dolor.
            </p>
            <p className="py-2 leading-8 text-gray-800 text-md">
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Distinctio consequatur nostrum molestias quidem. dolor.
            </p>
          </div>
          <div>
            <div>
              <Image src={web1} />
            </div>
            <div>
              <Image src={web2} />
            </div>
            <div>
              <Image src={web3} />
            </div>
            <div>
              <Image src={web4} />
            </div>
            <div>
              <Image src={web5} />
            </div>
            <div>
              <Image src={web6} />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
